const MAIN_BLUE_COLOR = '#545aef';
const MAIN_ORANGE_COLOR = '#fb8235';
const SUCCESS_COLOR = '#459f11';
const FAIL_COLOR = '#cc1515';
const PENDING_COLOR = '#646464';
const BOX_BORDER_COLOR = '#e5e5e5';
const DARK_COLOR = '#777777';
const DARK_COLOR2 = '#979797';
const LIGHT_COLOR = '#f8f8f8';
const LIGHT_COLOR2 = '#c9c9c9';

export { MAIN_BLUE_COLOR, MAIN_ORANGE_COLOR, SUCCESS_COLOR, FAIL_COLOR, PENDING_COLOR, BOX_BORDER_COLOR, DARK_COLOR, DARK_COLOR2, LIGHT_COLOR, LIGHT_COLOR2 };
